/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisfo.rizal;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author RizalZ
 */
public class datakaryawan extends javax.swing.JFrame {

    /**
     * Creates new form datakaryawan
     */
    public datakaryawan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TfNama = new javax.swing.JTextField();
        TfTempat = new javax.swing.JTextField();
        TfAgama = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        CbPendidikan = new javax.swing.JComboBox<>();
        CbJenis = new javax.swing.JComboBox<>();
        CbKeahlian1 = new javax.swing.JComboBox<>();
        CbJabatan = new javax.swing.JComboBox<>();
        CbKeahlian2 = new javax.swing.JComboBox<>();
        CbKeahlian3 = new javax.swing.JComboBox<>();
        CbKeahlian4 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        TfCari = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 13, 90, 30);

        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(545, 13, 70, 30);

        jLabel1.setText("DATA KARYAWAN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 20, 160, 14);
        getContentPane().add(TfNama);
        TfNama.setBounds(190, 70, 170, 30);
        getContentPane().add(TfTempat);
        TfTempat.setBounds(190, 110, 170, 30);
        getContentPane().add(TfAgama);
        TfAgama.setBounds(190, 250, 170, 30);

        jDateChooser1.setBackground(new java.awt.Color(0, 0, 128));
        jDateChooser1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(190, 160, 170, 30);

        CbPendidikan.setBackground(new java.awt.Color(0, 0, 128));
        CbPendidikan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SD", "SMP", "SMA / STM", "DIPLOMA", "SARJANA" }));
        getContentPane().add(CbPendidikan);
        CbPendidikan.setBounds(190, 290, 170, 30);

        CbJenis.setBackground(new java.awt.Color(0, 0, 128));
        CbJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LAKI - LAKI", "PEREMPUAN" }));
        CbJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbJenisActionPerformed(evt);
            }
        });
        getContentPane().add(CbJenis);
        CbJenis.setBounds(190, 210, 170, 30);

        CbKeahlian1.setBackground(new java.awt.Color(0, 0, 128));
        CbKeahlian1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PC", "SW", "JP", "CS", "MS", "PMA", "INS", "TK/C" }));
        getContentPane().add(CbKeahlian1);
        CbKeahlian1.setBounds(520, 70, 80, 30);

        CbJabatan.setBackground(new java.awt.Color(0, 0, 128));
        CbJabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MANAGER", "KEPALA LABORATORIUM", "BENDAHARA", "ADMINISTRASI KEUANGAN", "ANALIS", "ADMINISTRASI LABORATORIUM", "STAFF", "SAMPLER", "TALLYMAN" }));
        getContentPane().add(CbJabatan);
        CbJabatan.setBounds(190, 330, 170, 30);

        CbKeahlian2.setBackground(new java.awt.Color(0, 0, 128));
        CbKeahlian2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PC", "SW", "JP", "CS", "MS", "PMA", "INS", "TK/C" }));
        getContentPane().add(CbKeahlian2);
        CbKeahlian2.setBounds(520, 110, 80, 30);

        CbKeahlian3.setBackground(new java.awt.Color(0, 0, 128));
        CbKeahlian3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PC", "SW", "JP", "CS", "MS", "PMA", "INS", "TK/C" }));
        getContentPane().add(CbKeahlian3);
        CbKeahlian3.setBounds(520, 150, 80, 30);

        CbKeahlian4.setBackground(new java.awt.Color(0, 0, 128));
        CbKeahlian4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PC", "SW", "JP", "CS", "MS", "PMA", "INS", "TK/C" }));
        getContentPane().add(CbKeahlian4);
        CbKeahlian4.setBounds(520, 190, 80, 30);

        jLabel2.setBackground(new java.awt.Color(0, 0, 128));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAMA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 70, 90, 30);

        jLabel3.setBackground(new java.awt.Color(0, 0, 128));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TEMPAT LAHIR");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 110, 100, 30);

        jLabel4.setBackground(new java.awt.Color(0, 0, 128));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TANGGAL LAHIR");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 160, 100, 20);

        jLabel5.setBackground(new java.awt.Color(0, 0, 128));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("JENIS KELAMIN");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 204, 100, 40);

        jLabel6.setBackground(new java.awt.Color(0, 0, 128));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("AGAMA");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 250, 70, 20);

        jLabel7.setBackground(new java.awt.Color(0, 0, 128));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PENDIDIKAN TERAKHIR");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 290, 114, 30);

        jLabel8.setBackground(new java.awt.Color(0, 0, 128));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("JABATAN");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 330, 90, 20);

        jLabel9.setBackground(new java.awt.Color(0, 0, 128));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("KEAHLIAN 1");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(430, 80, 70, 20);

        jLabel10.setBackground(new java.awt.Color(0, 0, 128));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("KEAHLIAN 2");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(430, 120, 70, 20);

        jLabel11.setBackground(new java.awt.Color(0, 0, 128));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("KEAHLIAN 3");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(430, 160, 70, 20);

        jLabel12.setBackground(new java.awt.Color(0, 0, 128));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("KEAHLIAN 4");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(430, 200, 70, 20);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("SIMPAN");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(430, 230, 80, 30);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setText("CLEAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(530, 230, 80, 30);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setText("EDIT");
        getContentPane().add(jButton5);
        jButton5.setBounds(630, 230, 70, 30);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setText("PRINT");
        getContentPane().add(jButton6);
        jButton6.setBounds(470, 280, 73, 30);
        getContentPane().add(TfCari);
        TfCari.setBounds(430, 330, 90, 30);

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setText("CARI");
        getContentPane().add(jButton7);
        jButton7.setBounds(537, 330, 70, 30);

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setText("HAPUS");
        getContentPane().add(jButton8);
        jButton8.setBounds(615, 330, 80, 30);

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setText("UPDATE");
        getContentPane().add(jButton9);
        jButton9.setBounds(591, 280, 90, 30);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/BGdata.PNG"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(-100, 0, 830, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CbJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbJenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbJenisActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.setVisible(false);
    new pagemenu().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    TfNama.setText(""); 
    TfTempat.setText(""); 
    TfAgama.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
               // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datakaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datakaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datakaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datakaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datakaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbJabatan;
    private javax.swing.JComboBox<String> CbJenis;
    private javax.swing.JComboBox<String> CbKeahlian1;
    private javax.swing.JComboBox<String> CbKeahlian2;
    private javax.swing.JComboBox<String> CbKeahlian3;
    private javax.swing.JComboBox<String> CbKeahlian4;
    private javax.swing.JComboBox<String> CbPendidikan;
    private javax.swing.JTextField TfAgama;
    private javax.swing.JTextField TfCari;
    private javax.swing.JTextField TfNama;
    private javax.swing.JTextField TfTempat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
