/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisfo.rizal;

/**
 *
 * @author RizalZ
 */
public class gunakanjasa extends javax.swing.JFrame {
int PC,SW,FUMI,JP,CS,MS,PMA,a,b,c,d,e,f,g,h,i,total;
String PCprice,SWprice,FUMIprice,JPprice,CSprice,MSprice,PMAprice;
    /**
     * Creates new form gunakanjasa
     */
    public gunakanjasa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        TfPC = new javax.swing.JTextField();
        TfSW = new javax.swing.JTextField();
        TfJPC = new javax.swing.JTextField();
        TfJSW = new javax.swing.JTextField();
        TfJP = new javax.swing.JTextField();
        TfMS = new javax.swing.JTextField();
        TfPMA = new javax.swing.JTextField();
        TfFumigasi = new javax.swing.JTextField();
        TfJF = new javax.swing.JTextField();
        TfCS = new javax.swing.JTextField();
        TfTotal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/BGJASA.PNG"))); // NOI18N
        jLabel13.setText("jLabel13");
        jLabel13.setOpaque(true);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/BGJASA.PNG"))); // NOI18N
        jLabel16.setText("jLabel16");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 255));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 128));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PENGAMBIL CONTOH");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 10, 140, 20);

        jLabel2.setBackground(new java.awt.Color(0, 0, 128));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TON");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 40, 40, 20);

        jLabel3.setBackground(new java.awt.Color(0, 0, 128));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("JUMLAH");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 40, 60, 20);

        jLabel4.setBackground(new java.awt.Color(0, 0, 128));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MARINE SURVEY");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 234, 120, 20);

        jLabel5.setBackground(new java.awt.Color(0, 0, 128));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("JUMLAH");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(239, 340, 60, 20);

        jLabel6.setBackground(new java.awt.Color(0, 0, 128));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TOTAL");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(242, 400, 50, 20);

        jLabel7.setBackground(new java.awt.Color(0, 0, 128));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SWORN WEIGHER");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 74, 130, 20);

        jLabel8.setBackground(new java.awt.Color(0, 0, 128));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PENGUJI MUTU / ANALIS");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 274, 140, 20);

        jLabel9.setBackground(new java.awt.Color(0, 0, 128));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("JUMLAH");
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(239, 94, 60, 30);

        jLabel10.setBackground(new java.awt.Color(0, 0, 128));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TON");
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(130, 100, 40, 14);

        jLabel11.setBackground(new java.awt.Color(0, 0, 128));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("FUMIGASI");
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 310, 90, 20);

        jLabel12.setBackground(new java.awt.Color(0, 0, 128));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("JASA PENILAI");
        jLabel12.setOpaque(true);
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 160, 110, 20);

        jLabel14.setBackground(new java.awt.Color(0, 0, 128));
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("TON");
        jLabel14.setOpaque(true);
        getContentPane().add(jLabel14);
        jLabel14.setBounds(120, 340, 70, 20);

        jLabel15.setBackground(new java.awt.Color(0, 0, 128));
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("CARGO SURVEY");
        jLabel15.setOpaque(true);
        getContentPane().add(jLabel15);
        jLabel15.setBounds(30, 194, 110, 20);
        getContentPane().add(TfPC);
        TfPC.setBounds(30, 40, 90, 30);
        getContentPane().add(TfSW);
        TfSW.setBounds(30, 100, 90, 30);
        getContentPane().add(TfJPC);
        TfJPC.setBounds(330, 40, 100, 30);
        getContentPane().add(TfJSW);
        TfJSW.setBounds(330, 100, 100, 30);
        getContentPane().add(TfJP);
        TfJP.setBounds(330, 150, 100, 30);
        getContentPane().add(TfMS);
        TfMS.setBounds(330, 230, 100, 30);
        getContentPane().add(TfPMA);
        TfPMA.setBounds(330, 270, 100, 30);
        getContentPane().add(TfFumigasi);
        TfFumigasi.setBounds(30, 340, 80, 30);
        getContentPane().add(TfJF);
        TfJF.setBounds(330, 340, 100, 30);
        getContentPane().add(TfCS);
        TfCS.setBounds(330, 190, 100, 30);
        getContentPane().add(TfTotal);
        TfTotal.setBounds(330, 390, 100, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 440, 80, 30);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(350, 440, 70, 30);

        jCheckBox1.setBackground(new java.awt.Color(0, 0, 128));
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(170, 150, 30, 30);

        jCheckBox2.setBackground(new java.awt.Color(0, 0, 128));
        jCheckBox2.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox2ItemStateChanged(evt);
            }
        });
        getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(170, 190, 30, 30);

        jCheckBox3.setBackground(new java.awt.Color(0, 0, 128));
        jCheckBox3.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox3ItemStateChanged(evt);
            }
        });
        getContentPane().add(jCheckBox3);
        jCheckBox3.setBounds(170, 230, 30, 30);

        jCheckBox4.setBackground(new java.awt.Color(0, 0, 128));
        jCheckBox4.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox4ItemStateChanged(evt);
            }
        });
        getContentPane().add(jCheckBox4);
        jCheckBox4.setBounds(170, 270, 30, 30);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("HITUNG");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(30, 390, 90, 30);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setText("CLEAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(140, 390, 80, 30);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/BGJASA.PNG"))); // NOI18N
        jLabel17.setText("jLabel17");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(0, -40, 470, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.setVisible(false);      // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    PCprice = TfPC.getText();
    PC = Integer.parseInt(PCprice);
    a = PC * 1400;
    TfJPC.setText(String.valueOf(a));
    
    SWprice = TfSW.getText();
    SW = Integer.parseInt(SWprice);
    b = SW * 1500;
    TfJSW.setText(String.valueOf(b));
    
    FUMIprice = TfFumigasi.getText();
    FUMI = Integer.parseInt(FUMIprice);
    g = FUMI * 24200;
    TfJF.setText(String.valueOf(g));
    
    h = a + b + g;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
    if (jCheckBox1.isSelected()){
        c = 2500000;
    }
    else{
        c = 0;
    }
    TfJP.setText(String.valueOf(c));
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void jCheckBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox2ItemStateChanged
    if (jCheckBox2.isSelected()){
        d = 2000000;
    }
    else{
        d = 0;
    }
    TfCS.setText(String.valueOf(d));        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ItemStateChanged

    private void jCheckBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox3ItemStateChanged
    if (jCheckBox3.isSelected()){
        e = 15000000;
    }
    else{
        e = 0;
    }
    TfMS.setText(String.valueOf(e));        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ItemStateChanged

    private void jCheckBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox4ItemStateChanged
    if (jCheckBox4.isSelected()){
        f = 150000;
    }
    else{
        f = 0;
    }
    TfPMA.setText(String.valueOf(f));        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ItemStateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    TfPC.setText("");
    TfJPC.setText("");
    TfSW.setText("");
    TfJSW.setText("");
    TfJP.setText("");
    TfCS.setText("");
    TfMS.setText("");
    TfPMA.setText("");
    TfFumigasi.setText("");
    TfJF.setText("");
    TfTotal.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        i = h + c + d + e + f;
        TfTotal.setText(String.valueOf(i));        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gunakanjasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gunakanjasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gunakanjasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gunakanjasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gunakanjasa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TfCS;
    private javax.swing.JTextField TfFumigasi;
    private javax.swing.JTextField TfJF;
    private javax.swing.JTextField TfJP;
    private javax.swing.JTextField TfJPC;
    private javax.swing.JTextField TfJSW;
    private javax.swing.JTextField TfMS;
    private javax.swing.JTextField TfPC;
    private javax.swing.JTextField TfPMA;
    private javax.swing.JTextField TfSW;
    private javax.swing.JTextField TfTotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
