/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sisfo.rizal;

import javax.swing.JOptionPane;

/**
 *
 * @author RizalZ
 */
public class loginpage extends javax.swing.JFrame {

    /**
     * Creates new form loginpage
     */
    public loginpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TfUser = new javax.swing.JTextField();
        TfPassword = new javax.swing.JPasswordField();
        BLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BClear = new javax.swing.JButton();
        BExit = new javax.swing.JButton();
        CbLihat = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(TfUser);
        TfUser.setBounds(130, 50, 130, 30);
        getContentPane().add(TfPassword);
        TfPassword.setBounds(130, 100, 130, 30);

        BLogin.setText("LOGIN");
        BLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BLoginMouseClicked(evt);
            }
        });
        BLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLoginActionPerformed(evt);
            }
        });
        getContentPane().add(BLogin);
        BLogin.setBounds(20, 213, 100, 30);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USERNAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 50, 90, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PASSWORD");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 100, 80, 20);

        BClear.setText("CLEAR");
        BClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BClearActionPerformed(evt);
            }
        });
        getContentPane().add(BClear);
        BClear.setBounds(140, 213, 70, 30);

        BExit.setText("EXIT");
        BExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BExitActionPerformed(evt);
            }
        });
        getContentPane().add(BExit);
        BExit.setBounds(240, 213, 73, 30);

        CbLihat.setBackground(new java.awt.Color(0, 0, 128));
        CbLihat.setForeground(new java.awt.Color(255, 255, 255));
        CbLihat.setText("TAMPILKAN PASSWORD");
        CbLihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbLihatActionPerformed(evt);
            }
        });
        getContentPane().add(CbLihat);
        CbLihat.setBounds(130, 130, 170, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/BGLogin.PNG"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 330, 260);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BLoginMouseClicked
    String ext = new String(TfPassword.getPassword());
    if(TfUser.getText().equals("admin") && ext.equals("admin"))
            {
                JOptionPane.showMessageDialog(null, "Login Succesful");
                this.setVisible(false);
        new pagemenu().setVisible(true);
            } else
            {
                JOptionPane.showMessageDialog(null, "Login Failure");
            }
                  
    }//GEN-LAST:event_BLoginMouseClicked

    private void BLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLoginActionPerformed
 // Main Form to show after the Login Form..                  // TODO add your handling code here:
    }//GEN-LAST:event_BLoginActionPerformed

    private void BExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BExitActionPerformed
    System.exit(0);       // TODO add your handling code here:
    }//GEN-LAST:event_BExitActionPerformed

    private void CbLihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbLihatActionPerformed
        if (CbLihat.isSelected()) {
        TfPassword.setEchoChar((char)0);
        } else {
        TfPassword.setEchoChar('*');
    }        
    }//GEN-LAST:event_CbLihatActionPerformed

    private void BClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BClearActionPerformed
        TfUser.setText("");
        TfPassword.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_BClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new loginpage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BClear;
    private javax.swing.JButton BExit;
    private javax.swing.JButton BLogin;
    private javax.swing.JCheckBox CbLihat;
    private javax.swing.JPasswordField TfPassword;
    private javax.swing.JTextField TfUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    private void close() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
